spring.application.name=subscription-billing-system

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/billing_db
spring.datasource.username=root
spring.datasource.password=ROOT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.org.springframework=DEBUG

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
